"""
astra_reader.py
===============
A Python module for reading and extracting data from Wyatt ASTRA `.afe8` files.

ASTRA `.afe8` files are gzip-compressed SQLite databases containing data from
Gel Permeation Chromatography (GPC) / Size Exclusion Chromatography (SEC) runs,
including Multi-Angle Light Scattering (MALS), UV, Refractive Index (RI), and
Viscometer detector data.

Author: Generated by Goose
"""

from __future__ import annotations

import gzip
import sqlite3
import struct
import zlib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional, Union

import numpy as np

# ─────────────────────────────────────────────────────────────────────────────
# Enum / constant lookups
# ─────────────────────────────────────────────────────────────────────────────

# Instrument class -> human-readable name
INSTRUMENT_NAMES = {
    "WHeleos8Profile": "DAWN 8 (MALS)",
    "WHeleosNeonProfile": "DAWN Neon (MALS)",
    "WMiniDawnProfile": "miniDAWN (MALS)",
    "WNGOInstrumentProfile": "Optilab (RI)",
    "WGenericRIInstrumentProfile": "Generic RI",
    "WHplcUVDeviceProfile": "UV Detector",
    "WHplcDeviceProfile": "HPLC Device",
    "WHplcMultiDeviceProfile": "HPLC System",
    "WGenericUVInstrumentProfile": "Generic UV",
    "WGenericViscometerProfile": "Viscometer",
    "WViscoStarProfile": "ViscoStar",
    "WOptilab903Profile": "Optilab 903 (RI)",
    "WTreosProfile": "TREOS (MALS)",
}

MALS_PROFILE_TABLES = [
    "WHeleos8Profile",
    "WHeleosNeonProfile",
    "WMiniDawnProfile",
    "WTreosProfile",
]

# dataCategory values from WResultData / WScalarData / WVectorData / WMatrixData
DATA_CATEGORIES = {
    0: "raw",
    3: "fit_quality",
    4: "concentration",
    11: "MALS_results",
    12: "RI_results",
    14: "molar_mass",
    18: "polydispersity",
    21: "RI_analysis",
    22: "radius",
    25: "UV_analysis",
    26: "viscometer_results",
}

# Known m_nDataName integer codes -> descriptive strings
# These are enumerated values used throughout ASTRA for data series identification.
DATA_NAME_MAP = {
    # Raw signals
    12018: "MALS normalization factor",
    12021: "LS raw signal",
    12022: "LS multi-angle signal (matrix)",
    12025: "RI raw signal",
    12027: "Time",
    # Index units
    12068: "minutes",
    12069: "g/mol (molar mass)",
    12070: "nm (radius)",
    12072: "V (volts)",
    12074: "AU (absorbance units)",
    12075: "V (volts, normalized)",
    12098: "%",
    # Value names
    12012: "LS molar mass",
    12013: "concentration (g/mL)",
    12014: "detector number",
    12015: "LS normalized signal",
    12017: "RI signal (V)",
    12020: "molar mass (g/mol)",
    12027: "time (min)",
    12030: "raw light scattering",
    12031: "raw data collection",
    12054: "UV absorbance",
    12059: "temperature (°C)",
    12110: "UV signal (matrix)",
    12112: "specific viscosity",
    12113: "UV absorbance",
    12119: "processed chromatogram",
    12120: "Mn (number-average molar mass)",
    12121: "Mw (weight-average molar mass)",
    12122: "Mz (z-average molar mass)",
    12123: "radius (nm)",
    12128: "RMS radius (nm)",
    12161: "Mw/Mn (polydispersity)",
    12162: "Mz/Mw (polydispersity)",
    12189: "injected mass (g)",
    12190: "temperature",
    12230: "intrinsic viscosity (dL/g)",
    12285: "recovery fraction",
    12303: "MALS fit residual",
    12305: "MALS chi-squared",
    12306: "MALS Rg (radius of gyration)",
    12307: "MALS processed signal",
    12342: "MALS R(theta)/R(0) ratio",
    12343: "MALS fit coefficient",
    12395: "MALS second virial coefficient (A2)",
    12408: "mL (volume)",
    12409: "µg (mass)",
    12472: "molar mass (g/mol) from detector",
    12473: "Mw/Mn ratio (per detector)",
    12485: "empty/placeholder",
    12486: "channel number",
    12488: "RI voltage",
    12489: "RI raw voltage",
    12492: "MALS fit error",
    12493: "MALS third virial coefficient",
    12503: "radius (nm, low-angle)",
    12558: "intrinsic viscosity (dL/g)",
    12559: "specific viscosity",
    12560: "viscosity ratio",
    12566: "UV recovery fraction",
    12579: "HPLC device signal",
    12581: "HPLC pressure",
    12583: "HPLC flow rate",
    12585: "HPLC composition",
    12635: "HPLC units",
    # Viscometer specific
    2259: "specific viscosity",
    2370: "interdetector delay",
    2371: "delay percentage",
    2381: "normalization coefficient",
    2382: "second virial coefficient (A2)",
    2383: "elution volume (mL)",
    2408: "interdetector volume (mL)",
    2410: "peak volume (mL)",
    2411: "intrinsic viscosity (dL/g)",
    2412: "fit residual",
    2424: "peak area",
    3119: "auxiliary signal 1",
    3120: "auxiliary signal 2",
    2130: "injected mass (µg)",
}


def lookup_data_name(code: int) -> str:
    """Look up a human-readable name for a data name integer code."""
    return DATA_NAME_MAP.get(code, f"unknown_{code}")


def lookup_category(code: int) -> str:
    """Look up a human-readable name for a dataCategory code."""
    return DATA_CATEGORIES.get(code, f"category_{code}")


def lookup_instrument(class_name: str) -> str:
    """Look up a human-readable instrument name from the class name."""
    return INSTRUMENT_NAMES.get(class_name, class_name)


# ─────────────────────────────────────────────────────────────────────────────
# BLOB decoding
# ─────────────────────────────────────────────────────────────────────────────

def decode_blob(blob: bytes, is_double: bool = True) -> np.ndarray:
    """
    Decode an ASTRA data BLOB.

    BLOB format:
        - 16-byte header: 4 × uint32 (blob_size, uncompressed_size, count, element_size)
        - Remaining bytes: zlib-compressed data (magic 0x78 0x9c) OR raw data

    Parameters
    ----------
    blob : bytes
        The raw BLOB from the SQLite database.
    is_double : bool
        If True, interpret data as 8-byte doubles (float64).
        If False, interpret data as 4-byte floats (float32).

    Returns
    -------
    np.ndarray
        Array of decoded values.
    """
    if blob is None or len(blob) == 0:
        return np.array([])

    # Read 16-byte header
    if len(blob) >= 16:
        blob_size, uncomp_size, count, elem_size = struct.unpack_from("<4I", blob, 0)
        payload = blob[16:]
    else:
        payload = blob

    # Check for zlib compression (magic bytes 0x78 0x9c)
    if len(payload) >= 2 and payload[0] == 0x78 and payload[1] in (0x01, 0x9C, 0xDA):
        try:
            data = zlib.decompress(payload)
        except zlib.error:
            # Maybe the entire blob (including header) is compressed
            try:
                data = zlib.decompress(blob)
            except zlib.error:
                # Fall back to raw payload
                data = payload
    else:
        # Raw data (not compressed)
        data = payload

    # Interpret as doubles or floats
    if is_double:
        n = len(data) // 8
        if n == 0:
            return np.array([])
        return np.frombuffer(data[: n * 8], dtype="<f8").copy()
    else:
        n = len(data) // 4
        if n == 0:
            return np.array([])
        return np.frombuffer(data[: n * 4], dtype="<f4").copy()


def decode_raw_blob_doubles(blob: bytes) -> np.ndarray:
    """
    Decode a raw (non-compressed) BLOB that has a 16-byte header followed by doubles.
    Used for small blobs like detector angles and normalization coefficients.
    """
    if blob is None or len(blob) <= 16:
        return np.array([])
    data = blob[16:]
    n = len(data) // 8
    if n == 0:
        return np.array([])
    return np.frombuffer(data[: n * 8], dtype="<f8").copy()


def encode_blob(values: np.ndarray, is_double: bool = True) -> bytes:
    """
    Encode a NumPy array into an ASTRA-compatible BLOB.

    This is the inverse of :func:`decode_blob`.  The BLOB format is a 16-byte
    header (4 x uint32: blob_size, uncompressed_size, count, element_size)
    followed by zlib-compressed payload data.

    Parameters
    ----------
    values : np.ndarray
        1-D array of values to encode.
    is_double : bool
        If True (default), encode as 8-byte doubles (float64).
        If False, encode as 4-byte floats (float32).

    Returns
    -------
    bytes
        The encoded BLOB ready to write into a SQLite BLOB column.
    """
    if values is None or len(values) == 0:
        elem_size = 8 if is_double else 4
        header = struct.pack("<4I", 16, 0, 0, elem_size)
        return header

    arr = np.asarray(values, dtype=("<f8" if is_double else "<f4"))
    raw_payload = arr.tobytes()
    compressed = zlib.compress(raw_payload, level=6)

    elem_size = 8 if is_double else 4
    count = len(arr)
    blob_size = 16 + len(compressed)
    uncomp_size = len(raw_payload)

    header = struct.pack("<4I", blob_size, uncomp_size, count, elem_size)
    return header + compressed


def encode_raw_blob_doubles(values: np.ndarray) -> bytes:
    """
    Encode a NumPy array into a raw (non-compressed) BLOB with 16-byte header.

    This is the inverse of :func:`decode_raw_blob_doubles`.
    """
    arr = np.asarray(values, dtype="<f8")
    raw_payload = arr.tobytes()
    count = len(arr)
    elem_size = 8
    blob_size = 16 + len(raw_payload)
    header = struct.pack("<4I", blob_size, len(raw_payload), count, elem_size)
    return header + raw_payload


# ─────────────────────────────────────────────────────────────────────────────
# Data classes
# ─────────────────────────────────────────────────────────────────────────────

@dataclass
class ExperimentInfo:
    """Top-level experiment metadata."""
    group_id: str = ""
    object_id: str = ""
    path: str = ""
    sample_set_file: str = ""
    collection_astra_version: int = 0
    processing_datetime: str = ""
    signature_validation_datetime: str = ""


@dataclass
class FileInfo:
    """File-level metadata."""
    directory: str = ""
    file_name: str = ""
    file_extension: str = ""
    time_created: str = ""
    time_modified: str = ""
    time_collected: str = ""
    author: str = ""
    title: str = ""
    subject: str = ""
    category: str = ""
    keywords: str = ""
    comments: str = ""
    size: int = 0


@dataclass
class SolventInfo:
    """Solvent profile information."""
    name: str = ""
    description: str = ""
    refractive_index_model: int = 0
    viscosity_model: int = 0
    rayleigh_ratio_model: int = 0
    reference_temperature: float = 25.0
    reference_wavelength: float = 658.0
    melting_point: float = 0.0
    boiling_point: float = 0.0


@dataclass
class MALSInfo:
    """Multi-Angle Light Scattering (DAWN) detector configuration."""
    name: str = ""
    description: str = ""
    temperature: float = 25.0
    wavelength: float = 658.0
    num_detectors: int = 8
    calibration_constant: float = 1.0
    detector_angles: np.ndarray = field(default_factory=lambda: np.array([]))
    normalization_coefficients: np.ndarray = field(default_factory=lambda: np.array([]))
    instrumental_term: float = 1.0
    mixing_term: float = 50.0
    firmware_version: str = ""


@dataclass
class RIInfo:
    """Refractive Index detector configuration."""
    name: str = ""
    temperature: float = 25.0
    wavelength: float = 658.0
    calibration_constant: float = 1.0


@dataclass
class UVInfo:
    """UV detector configuration."""
    name: str = ""
    description: str = ""
    cell_length: float = 10.0
    active_channel: int = 0
    wavelengths: list = field(default_factory=list)


@dataclass
class ViscometerInfo:
    """Viscometer detector configuration."""
    name: str = ""
    temperature: float = 25.0
    dilution_factor: float = 0.5
    use_specific_viscosity: bool = False
    enable_dilution_correction: bool = False


@dataclass
class SampleInfo:
    """Injected sample information."""
    name: str = ""
    description: str = ""
    dn_dc: float = 0.0
    a2: float = 0.0
    wavelength: float = 0.0
    uv_extinction_coefficient: float = 0.0
    concentration: float = 0.0
    reference_temperature: float = 25.0
    real_ri: float = 0.0
    imaginary_ri: float = 0.0
    mhs_k: float = 0.0
    mhs_a: float = 0.0
    primary_uv_wavelength: float = 0.0
    secondary_uv_wavelength: float = 0.0


@dataclass
class PeakRange:
    """Peak range definition."""
    range_number: int = 0
    range_name: str = ""
    range_start: float = 0.0  # minutes
    range_end: float = 0.0  # minutes
    radius: float = 0.0
    radius_type: int = 0
    a2: float = 0.0
    dn_dc: float = 0.0
    real_ri: float = 0.0
    uv_extinction_coefficient: float = 0.0
    concentration: float = 0.0
    injected_mass: float = 0.0
    ls_model: int = 0
    ls_fit_degree: int = 1
    molar_mass: float = 0.0
    intrinsic_viscosity: float = 0.0
    mn: float = 0.0
    mw: float = 0.0
    max_value: float = 0.0
    max_index: float = 0.0


@dataclass
class VectorData:
    """A single vector (1-D time series) data series."""
    data_name_code: int = 0
    data_name: str = ""
    value_name_code: int = 0
    value_name: str = ""
    value_units_code: int = 0
    index_name_code: int = 0
    index_name: str = ""
    index_units_code: int = 0
    index_units: str = ""
    peak: int = 0
    instrument_class: str = ""
    instrument_name: str = ""
    data_category: int = 0
    is_true_double: bool = True
    index_values: np.ndarray = field(default_factory=lambda: np.array([]))
    data_values: np.ndarray = field(default_factory=lambda: np.array([]))


@dataclass
class MatrixData:
    """A 2-D matrix data series (e.g., MALS multi-angle data)."""
    data_name_code: int = 0
    data_name: str = ""
    value_name_code: int = 0
    value_name: str = ""
    index_name_code: int = 0
    index_name: str = ""
    index_units_code: int = 0
    index_units: str = ""
    column_index_name_code: int = 0
    column_index_name: str = ""
    peak: int = 0
    instrument_class: str = ""
    instrument_name: str = ""
    data_category: int = 0
    is_true_double: bool = True
    row_index: np.ndarray = field(default_factory=lambda: np.array([]))
    column_index: np.ndarray = field(default_factory=lambda: np.array([]))
    values: np.ndarray = field(default_factory=lambda: np.array([]))  # shape: (n_rows, n_cols)


@dataclass
class ResultData:
    """A single computed result (scalar value)."""
    data_name_code: int = 0
    data_name: str = ""
    value_units_code: int = 0
    value_name_code: int = 0
    value_name: str = ""
    peak: int = 0
    instrument_class: str = ""
    instrument_name: str = ""
    data_category: int = 0
    category_name: str = ""
    value: float = 0.0
    high_uncertainty: float = 0.0
    low_uncertainty: float = 0.0
    index_value: float = 0.0
    index_name_code: int = 0
    index_units_code: int = 0


@dataclass
class FluidConnection:
    """Fluid connection between two instruments."""
    name: str = ""
    description: str = ""
    source_instrument: str = ""
    destination_instrument: str = ""
    interdetector_volume: float = 0.0
    temperature: float = 25.0


# ─────────────────────────────────────────────────────────────────────────────
# Main reader class
# ─────────────────────────────────────────────────────────────────────────────

class AstraReader:
    """
    Read and extract data from Wyatt ASTRA `.afe8` files.

    Parameters
    ----------
    file_path : str or Path
        Path to the `.afe8` file.

    Examples
    --------
    >>> reader = AstraReader("sample.afe8")
    >>> print(reader.experiment)
    >>> mals_data = reader.get_mals_chromatogram()
    >>> ri_data = reader.get_ri_chromatogram()
    >>> results = reader.get_results()
    """

    def __init__(self, file_path: Union[str, Path]):
        self.file_path = Path(file_path)
        self._conn: Optional[sqlite3.Connection] = None
        self._load()

    def _load(self) -> None:
        """Decompress the gzip file and open the SQLite database."""
        import tempfile

        with gzip.open(self.file_path, "rb") as f:
            db_bytes = f.read()

        # Write decompressed SQLite database to a temp file
        self._temp_file = tempfile.NamedTemporaryFile(
            suffix=".sqlite", delete=False, prefix="astra_"
        )
        self._temp_file.write(db_bytes)
        self._temp_file.close()

        uri_path = self._temp_file.name.replace("\\", "/")
        self._conn = sqlite3.connect(f"file:{uri_path}?mode=ro", uri=True)
        self._conn.execute("PRAGMA query_only=ON;")
        self._conn.row_factory = None  # Default — tuples
        self._mals_table: Optional[str] = None

    def __del__(self):
        self.close()
        # Clean up temp file
        if hasattr(self, "_temp_file") and hasattr(self._temp_file, "name"):
            try:
                import os
                os.unlink(self._temp_file.name)
            except OSError:
                pass

    def close(self) -> None:
        """Close the database connection."""
        if self._conn is not None:
            self._conn.close()
            self._conn = None

    def _query(self, sql: str, params: tuple = ()) -> list:
        """Execute a SQL query and return all rows."""
        cur = self._conn.cursor()
        cur.execute(sql, params)
        rows = cur.fetchall()
        cur.close()
        return rows

    def _query_one(self, sql: str, params: tuple = ()) -> Optional[tuple]:
        """Execute a SQL query and return the first row."""
        cur = self._conn.cursor()
        cur.execute(sql, params)
        row = cur.fetchone()
        cur.close()
        return row

    @staticmethod
    def _guid_str(blob_or_str) -> str:
        """Convert a GUID (stored as string or BLOB) to a clean string."""
        if isinstance(blob_or_str, str):
            return blob_or_str
        if isinstance(blob_or_str, (bytes, bytearray)):
            return blob_or_str.decode("utf-8", errors="replace")
        return str(blob_or_str)

    def _resolve_mals_table(self) -> Optional[str]:
        """Return the name of the first present MALS profile table, cached."""
        if self._mals_table is not None:
            return self._mals_table if self._mals_table != "" else None
        tables = set(self.list_tables())
        for candidate in MALS_PROFILE_TABLES:
            if candidate in tables:
                self._mals_table = candidate
                return candidate
        self._mals_table = ""
        return None

    # ── Experiment metadata ──────────────────────────────────────────────

    @property
    def experiment(self) -> ExperimentInfo:
        """Return the top-level experiment info."""
        row = self._query_one("SELECT * FROM WExperiment LIMIT 1")
        if row is None:
            return ExperimentInfo()
        cols = [d[0] for d in self._conn.execute("SELECT * FROM WExperiment LIMIT 1").description]
        d = dict(zip(cols, row, strict=False))
        return ExperimentInfo(
            group_id=self._guid_str(d.get("groupID", "")),
            object_id=self._guid_str(d.get("objectID", "")),
            path=d.get("path", "") or "",
            sample_set_file=d.get("m_sSampleSetFileName", "") or "",
            collection_astra_version=d.get("m_nCollectionAstraVersion", 0) or 0,
            processing_datetime=str(d.get("processingDateTime", "")) or "",
            signature_validation_datetime=str(d.get("signatureValidationDateTime", "")) or "",
        )

    @property
    def file_info(self) -> FileInfo:
        """Return file-level metadata from WFileEntry."""
        row = self._query_one("SELECT * FROM WFileEntry LIMIT 1")
        if row is None:
            return FileInfo()
        cols = [d[0] for d in self._conn.execute("SELECT * FROM WFileEntry LIMIT 1").description]
        d = dict(zip(cols, row, strict=False))
        return FileInfo(
            directory=d.get("directory", "") or "",
            file_name=d.get("fileName", "") or "",
            file_extension=d.get("fileExt", "") or "",
            time_created=str(d.get("m_TimeCreated", "")) or "",
            time_modified=str(d.get("m_TimeModified", "")) or "",
            time_collected=str(d.get("timeCollected", "")) or "",
            author=d.get("m_sAuthor", "") or "",
            title=d.get("m_sTitle", "") or "",
            subject=d.get("m_sSubject", "") or "",
            category=d.get("m_sCategory", "") or "",
            keywords=d.get("m_sKeywords", "") or "",
            comments=d.get("m_sComments", "") or "",
            size=(d.get("m_nSizeHigh", 0) or 0) * (2**32) + (d.get("m_nSizeLow", 0) or 0),
        )

    @property
    def solvent(self) -> SolventInfo:
        """Return solvent profile info."""
        row = self._query_one("SELECT * FROM WSolventProfile LIMIT 1")
        if row is None:
            return SolventInfo()
        cols = [d[0] for d in self._conn.execute("SELECT * FROM WSolventProfile LIMIT 1").description]
        d = dict(zip(cols, row, strict=False))
        return SolventInfo(
            name=d.get("m_sName", "") or "",
            description=d.get("m_sDescription", "") or "",
            refractive_index_model=d.get("m_nRefractiveIndexModel", 0) or 0,
            viscosity_model=d.get("m_nViscosityModel", 0) or 0,
            rayleigh_ratio_model=d.get("m_nRayleighRatioModel", 0) or 0,
            reference_temperature=d.get("m_dReferenceTemperature", 25.0) or 25.0,
            reference_wavelength=d.get("m_dReferenceWavelength", 658.0) or 658.0,
            melting_point=d.get("dMeltingPoint", 0.0) or 0.0,
            boiling_point=d.get("dBoilingPoint", 0.0) or 0.0,
        )

    @property
    def mals(self) -> MALSInfo:
        """Return MALS (DAWN) detector info."""
        table = self._resolve_mals_table()
        if table is None:
            return MALSInfo()
        row = self._query_one(f'SELECT * FROM "{table}" LIMIT 1')
        if row is None:
            return MALSInfo()
        cols = [d[0] for d in self._conn.execute(f'SELECT * FROM "{table}" LIMIT 1').description]
        d = dict(zip(cols, row, strict=False))
        angles = decode_raw_blob_doubles(d.get("m_vDetectorAngles", b""))
        norm_coeffs = decode_raw_blob_doubles(d.get("m_vNormalizationCoefficients", b""))
        num_detectors = d.get("m_nNumberOfDetectors", 8) or 8
        # The angles blob can carry a trailing spurious value beyond the actual
        # detector count (e.g. 9 doubles for an 8-detector DAWN). Trim to the
        # reported detector count so the metadata matches the signal columns.
        if num_detectors and len(angles) > num_detectors:
            angles = angles[:num_detectors]
        return MALSInfo(
            name=d.get("m_sName", "") or "",
            description=d.get("m_sDescription", "") or "",
            temperature=d.get("m_dTemperature", 25.0) or 25.0,
            wavelength=d.get("m_dWavelength", 658.0) or 658.0,
            num_detectors=num_detectors,
            calibration_constant=d.get("m_dCalibrationConstant", 1.0) or 1.0,
            detector_angles=angles,
            normalization_coefficients=norm_coeffs,
            instrumental_term=d.get("m_dInstrumentalTerm", 1.0) or 1.0,
            mixing_term=d.get("m_dMixingTerm", 50.0) or 50.0,
            firmware_version=d.get("firmwareVersion", "") or "",
        )

    @property
    def ri(self) -> RIInfo:
        """Return RI (Optilab) detector info."""
        # Try WNGOInstrumentProfile first, then WGenericRIInstrumentProfile
        row = self._query_one("SELECT * FROM WNGOInstrumentProfile LIMIT 1")
        if row is None:
            return RIInfo()
        cols = [d[0] for d in self._conn.execute("SELECT * FROM WNGOInstrumentProfile LIMIT 1").description]
        d = dict(zip(cols, row, strict=False))
        return RIInfo(
            name=d.get("m_sName", "") or "",
            temperature=d.get("m_dTemperature", 25.0) or 25.0,
            wavelength=d.get("m_dWavelength", 658.0) or 658.0,
            calibration_constant=d.get("m_dCalibrationConstant", 1.0) or 1.0,
        )

    @property
    def uv(self) -> UVInfo:
        """Return UV detector info."""
        row = self._query_one("SELECT * FROM WHplcUVDeviceProfile LIMIT 1")
        if row is None:
            # Try generic UV
            row = self._query_one("SELECT * FROM WGenericUVInstrumentProfile LIMIT 1")
            if row is None:
                return UVInfo()
            cols = [d[0] for d in self._conn.execute("SELECT * FROM WGenericUVInstrumentProfile LIMIT 1").description]
        else:
            cols = [d[0] for d in self._conn.execute("SELECT * FROM WHplcUVDeviceProfile LIMIT 1").description]
        d = dict(zip(cols, row, strict=False))

        # Decode wavelengths blob (present on WGenericUVInstrumentProfile)
        wavelengths = []
        wl_blob = d.get("m_vWavelengths")
        if wl_blob and isinstance(wl_blob, (bytes, bytearray)):
            wl_data = decode_raw_blob_doubles(wl_blob)
            wavelengths = wl_data.tolist()

        # WHplcUVDeviceProfile does not store the wavelengths in a blob; it only
        # records the channel counts/indices.  The actual monitored wavelengths
        # live on the injected-sample profile (primary/secondary UV wavelength).
        # Fall back to those so the UI shows real nm values instead of channel
        # numbers (which previously surfaced as "1 nm" / "2 nm").
        if not wavelengths:
            num_channels = (
                d.get("numberUVChannels")
                or d.get("m_nNumberUVChannels")
                or 0
            )
            primary = d.get("primaryUVWavelength")
            secondary = d.get("secondaryUVWavelength")
            if primary is None or secondary is None:
                samp = self.sample
                if primary is None:
                    primary = samp.primary_uv_wavelength
                if secondary is None:
                    secondary = samp.secondary_uv_wavelength
            candidates = [w for w in (primary, secondary) if w]
            if candidates:
                if num_channels and num_channels <= len(candidates):
                    wavelengths = candidates[:num_channels]
                else:
                    wavelengths = candidates

        cell_length = (
            d.get("m_dCellLength")
            or d.get("cellLength")
            or 10.0
        )
        active_channel = (
            d.get("m_activeChannel")
            or d.get("activeChannel")
            or 0
        )

        return UVInfo(
            name=d.get("m_sName", "") or "",
            description=d.get("m_sDescription", "") or "",
            cell_length=cell_length,
            active_channel=active_channel,
            wavelengths=wavelengths,
        )

    @property
    def viscometer(self) -> ViscometerInfo:
        """Return viscometer info."""
        row = self._query_one("SELECT * FROM WGenericViscometerProfile LIMIT 1")
        if row is None:
            return ViscometerInfo()
        cols = [d[0] for d in self._conn.execute("SELECT * FROM WGenericViscometerProfile LIMIT 1").description]
        d = dict(zip(cols, row, strict=False))
        return ViscometerInfo(
            name=d.get("m_sName", "") or "",
            temperature=d.get("m_dTemperature", 25.0) or 25.0,
            dilution_factor=d.get("m_dDilutionFactor", 0.5) or 0.5,
            use_specific_viscosity=bool(d.get("m_bUseSpecificViscosity", 0)),
            enable_dilution_correction=bool(d.get("m_bEnableDilutionCorrection", 0)),
        )

    @property
    def sample(self) -> SampleInfo:
        """Return injected sample info."""
        row = self._query_one("SELECT * FROM WInjectedSampleProfile LIMIT 1")
        if row is None:
            return SampleInfo()
        cols = [d[0] for d in self._conn.execute("SELECT * FROM WInjectedSampleProfile LIMIT 1").description]
        d = dict(zip(cols, row, strict=False))
        return SampleInfo(
            name=d.get("m_sName", "") or "",
            description=d.get("m_sDescription", "") or "",
            dn_dc=d.get("m_dDNDC", 0.0) or 0.0,
            a2=d.get("m_dA2", 0.0) or 0.0,
            wavelength=d.get("m_dWavelength", 0.0) or 0.0,
            uv_extinction_coefficient=d.get("m_dUVExtinctionCoefficient", 0.0) or 0.0,
            concentration=d.get("m_dConcentration", 0.0) or 0.0,
            reference_temperature=d.get("m_dReferenceTemperature", 25.0) or 25.0,
            real_ri=d.get("dRealRI", 0.0) or 0.0,
            imaginary_ri=d.get("dImaginaryRI", 0.0) or 0.0,
            mhs_k=d.get("m_dMHS_K", 0.0) or 0.0,
            mhs_a=d.get("m_dMHS_a", 0.0) or 0.0,
            primary_uv_wavelength=d.get("primaryUVWavelength", 0.0) or 0.0,
            secondary_uv_wavelength=d.get("secondaryUVWavelength", 0.0) or 0.0,
        )

    @property
    def peaks(self) -> list[PeakRange]:
        """Return list of peak ranges."""
        rows = self._query("SELECT * FROM WPeakRange ORDER BY rangeNumber")
        if not rows:
            return []
        cols = [d[0] for d in self._conn.execute("SELECT * FROM WPeakRange LIMIT 1").description]
        result = []
        for row in rows:
            d = dict(zip(cols, row, strict=False))
            result.append(PeakRange(
                range_number=d.get("rangeNumber", 0) or 0,
                range_name=d.get("rangeName", "") or "",
                range_start=d.get("rangeStart", 0.0) or 0.0,
                range_end=d.get("rangeEnd", 0.0) or 0.0,
                radius=d.get("m_dRadius", 0.0) or 0.0,
                radius_type=d.get("m_nRadiusType", 0) or 0,
                a2=d.get("m_dA2", 0.0) or 0.0,
                dn_dc=d.get("m_dDNDC", 0.0) or 0.0,
                real_ri=d.get("m_dRealRI", 0.0) or 0.0,
                uv_extinction_coefficient=d.get("m_dUVExtinctionCoefficient", 0.0) or 0.0,
                concentration=d.get("m_dConcentration", 0.0) or 0.0,
                injected_mass=d.get("m_dInjectedMass", 0.0) or 0.0,
                ls_model=d.get("m_nLSModel", 0) or 0,
                ls_fit_degree=d.get("m_nLSFitDegree", 1) or 1,
                molar_mass=d.get("m_dMolarMass", 0.0) or 0.0,
                intrinsic_viscosity=d.get("m_dIntrinsicViscosity", 0.0) or 0.0,
                mn=d.get("Mn", 0.0) or 0.0,
                mw=d.get("Mw", 0.0) or 0.0,
                max_value=d.get("m_maxValue", 0.0) or 0.0,
                max_index=d.get("m_maxIndex", 0.0) or 0.0,
            ))
        return result

    @property
    def fluid_connections(self) -> list[FluidConnection]:
        """Return the fluid connection chain (instrument flow path)."""
        rows = self._query("SELECT * FROM WFluidConnectionProfile ORDER BY timestamp")
        if not rows:
            return []
        cols = [d[0] for d in self._conn.execute("SELECT * FROM WFluidConnectionProfile LIMIT 1").description]
        result = []
        for row in rows:
            d = dict(zip(cols, row, strict=False))
            result.append(FluidConnection(
                name=d.get("m_sName", "") or "",
                description=d.get("m_sDescription", "") or "",
                source_instrument=d.get("m_sSourceInstrument", "") or "",
                destination_instrument=d.get("m_sDestinationInstrument", "") or "",
                interdetector_volume=d.get("m_dInterdetectorVolume", 0.0) or 0.0,
                temperature=d.get("m_dTemperature", 25.0) or 25.0,
            ))
        return result

    # ── Data extraction ─────────────────────────────────────────────────

    @property
    def vector_data(self) -> list[VectorData]:
        """Return all vector (1-D time-series) data series."""
        rows = self._query("""
            SELECT m_nDataName, m_nValueName, m_nValueUnits, m_nIndexName, m_nIndexUnits,
                   m_nPeak, m_sInstrumentClassName, dataCategory, m_bTrueDouble,
                   m_vIndex, m_vValue
            FROM WVectorData
            ORDER BY m_sInstrumentClassName, m_nDataName
        """)
        result = []
        for row in rows:
            (dname_code, vname_code, vunits_code, iname_code, iunits_code,
             peak, inst_class, dcat, true_dbl, v_idx, v_val) = row

            # Determine if data is doubles or floats
            is_double = true_dbl == 1

            # Decode index (always doubles)
            idx_vals = decode_blob(v_idx, is_double=True)

            # Decode values
            val_vals = decode_blob(v_val, is_double=is_double)

            result.append(VectorData(
                data_name_code=dname_code or 0,
                data_name=lookup_data_name(dname_code or 0),
                value_name_code=vname_code or 0,
                value_name=lookup_data_name(vname_code or 0),
                value_units_code=vunits_code or 0,
                index_name_code=iname_code or 0,
                index_name=lookup_data_name(iname_code or 0),
                index_units_code=iunits_code or 0,
                index_units=lookup_data_name(iunits_code or 0),
                peak=peak or 0,
                instrument_class=inst_class or "",
                instrument_name=lookup_instrument(inst_class or ""),
                data_category=dcat or 0,
                is_true_double=bool(true_dbl),
                index_values=idx_vals,
                data_values=val_vals,
            ))
        return result

    @property
    def matrix_data(self) -> list[MatrixData]:
        """Return all matrix (2-D) data series."""
        rows = self._query("""
            SELECT m_nDataName, m_nValueName, m_nIndexName, m_nIndexUnits,
                   m_nColumnIndexName, m_nPeak, m_sInstrumentClassName,
                   dataCategory, m_bTrueDouble, m_vIndex, m_vColumnIndex, m_vvValue
            FROM WMatrixData
            ORDER BY m_sInstrumentClassName, m_nDataName
        """)
        result = []
        for row in rows:
            (dname_code, vname_code, iname_code, iunits_code,
             ciname_code, peak, inst_class, dcat, true_dbl,
             v_idx, v_cidx, v_val) = row

            is_double = true_dbl == 1

            # Row index (time axis) - always doubles
            row_idx = decode_blob(v_idx, is_double=True)

            # Column index (detector/channel numbers) - raw doubles (no zlib)
            col_idx = decode_raw_blob_doubles(v_cidx)

            # Values matrix
            val_1d = decode_blob(v_val, is_double=is_double)
            n_cols = len(col_idx) if len(col_idx) > 0 else 0
            n_rows = len(row_idx) if len(row_idx) > 0 else 0
            if n_cols > 0 and n_rows > 0 and len(val_1d) == n_rows * n_cols:
                values = val_1d.reshape(n_rows, n_cols)
            elif n_cols > 0 and len(val_1d) % n_cols == 0:
                values = val_1d.reshape(-1, n_cols)
            else:
                values = val_1d  # Flat array as fallback

            result.append(MatrixData(
                data_name_code=dname_code or 0,
                data_name=lookup_data_name(dname_code or 0),
                value_name_code=vname_code or 0,
                value_name=lookup_data_name(vname_code or 0),
                index_name_code=iname_code or 0,
                index_name=lookup_data_name(iname_code or 0),
                index_units_code=iunits_code or 0,
                index_units=lookup_data_name(iunits_code or 0),
                column_index_name_code=ciname_code or 0,
                column_index_name=lookup_data_name(ciname_code or 0),
                peak=peak or 0,
                instrument_class=inst_class or "",
                instrument_name=lookup_instrument(inst_class or ""),
                data_category=dcat or 0,
                is_true_double=bool(true_dbl),
                row_index=row_idx,
                column_index=col_idx,
                values=values,
            ))
        return result

    @property
    def results(self) -> list[ResultData]:
        """Return all computed result data."""
        rows = self._query("""
            SELECT m_nDataName, m_nValueUnits, m_nValueName, m_nPeak,
                   m_sInstrumentClassName, dataCategory, m_dValue,
                   m_dHighUncertainty, m_dLowUncertainty,
                   indexValue, indexName, indexUnits
            FROM WResultData
            ORDER BY m_nPeak, m_sInstrumentClassName, m_nDataName
        """)
        result = []
        for row in rows:
            (dname_code, vunits_code, vname_code, peak,
             inst_class, dcat, value, hi_unc, lo_unc,
             idx_val, idx_name_code, idx_units_code) = row
            result.append(ResultData(
                data_name_code=dname_code or 0,
                data_name=lookup_data_name(dname_code or 0),
                value_units_code=vunits_code or 0,
                value_name_code=vname_code or 0,
                value_name=lookup_data_name(vname_code or 0),
                peak=peak or 0,
                instrument_class=inst_class or "",
                instrument_name=lookup_instrument(inst_class or "") if inst_class and inst_class.strip() else "Combined",
                data_category=dcat or 0,
                category_name=lookup_category(dcat or 0),
                value=value or 0.0,
                high_uncertainty=hi_unc or 0.0,
                low_uncertainty=lo_unc or 0.0,
                index_value=idx_val or 0.0,
                index_name_code=idx_name_code or 0,
                index_units_code=idx_units_code or 0,
            ))
        return result

    # ── Convenience methods ───────────────────────────────────────────────

    def get_mals_chromatogram(self) -> Optional[MatrixData]:
        """
        Return the MALS multi-angle chromatogram matrix.

        This is the raw light scattering signal from all 8 DAWN detectors
        as a function of elution time.

        Returns
        -------
        MatrixData or None
            Matrix where rows are time points and columns are detector angles.
        """
        # Prefer the multi-angle matrix (data_name 12022, "LS multi-angle
        # signal") which carries one column per detector angle.  Fall back to
        # the "LS raw signal" matrix (12021) only if the multi-angle one is
        # missing.  Both codes exist in some files, and 12021 may contain
        # fewer columns than the true detector count, so ordering matters.
        for target_code in (12022, 12021):
            best = None
            for m in self.matrix_data:
                if m.instrument_class in MALS_PROFILE_TABLES and m.data_name_code == target_code:
                    if m.values.ndim == 2 and m.values.shape[1] > 1:
                        if best is None or m.values.shape[1] > best.values.shape[1]:
                            best = m
            if best is not None:
                return best
        # Fallback: any MALS matrix
        for m in self.matrix_data:
            if m.instrument_class in MALS_PROFILE_TABLES:
                return m
        return None

    def get_ri_chromatogram(self) -> Optional[VectorData]:
        """
        Return the RI (refractive index) detector chromatogram.

        Returns
        -------
        VectorData or None
            Time series of RI signal vs. elution time.

        Notes
        -----
        The Optilab (``WNGOInstrumentProfile``) table carries several vectors.
        The true dRI chromatogram — the one that shows a clean baseline with the
        elution peak, matching what ASTRA displays — is **data_name 12025**
        ("RI raw signal").  Code 12021 under this table is an auxiliary signal
        that is essentially flat and peaks near the void volume, so preferring it
        made the RI trace look "all over the place".  We therefore prefer 12025,
        then fall back to the RI raw voltage (12489), and only then to 12021.
        """
        preference = (12025, 12489, 12021)
        for target_code in preference:
            for v in self.vector_data:
                if (
                    v.instrument_class == "WNGOInstrumentProfile"
                    and v.data_name_code == target_code
                    and len(v.data_values) > 10
                ):
                    return v
        # Fallback: any WNGO vector with enough points.
        for v in self.vector_data:
            if v.instrument_class == "WNGOInstrumentProfile" and len(v.data_values) > 10:
                return v
        return None

    def get_uv_chromatogram(self) -> Optional[MatrixData]:
        """
        Return the UV detector chromatogram (multi-channel).

        Returns
        -------
        MatrixData or None
            Matrix where rows are time points and columns are UV channels.
        """
        for m in self.matrix_data:
            if m.instrument_class == "WHplcUVDeviceProfile":
                return m
        # Fallback: any UV matrix
        for m in self.matrix_data:
            if "UV" in m.instrument_class or "HplcUV" in m.instrument_class:
                return m
        return None

    def get_molar_mass_results(self) -> dict:
        """
        Return key molar mass results (Mn, Mw, Mz, polydispersity).

        Returns
        -------
        dict
            Dictionary with keys: Mn, Mw, Mz, Pd_MwMn, Pd_MzMw, and per-detector values.
        """
        results = {}
        for r in self.results:
            if r.data_name_code == 12120:
                results["Mn"] = r.value
            elif r.data_name_code == 12121:
                results["Mw"] = r.value
            elif r.data_name_code == 12122:
                results["Mz"] = r.value
            elif r.data_name_code == 12161:
                results["Pd_MwMn"] = r.value  # Mw/Mn
            elif r.data_name_code == 12162:
                results["Pd_MzMw"] = r.value  # Mz/Mw
            elif r.data_name_code == 12123:
                results["radius"] = r.value
            elif r.data_name_code == 12128:
                results["RMS_radius"] = r.value
            elif r.data_name_code == 12472:
                key = f"Mw_{r.instrument_name}"
                results[key] = r.value
        return results

    def get_all_results_by_peak(self, peak: int = 1) -> list[ResultData]:
        """Return all results for a given peak number."""
        return [r for r in self.results if r.peak == peak]

    def get_summary(self) -> dict:
        """
        Return a summary dictionary of the entire experiment.

        Returns
        -------
        dict
            Nested dictionary with experiment, file, solvent, instruments,
            sample, peaks, and key results.
        """
        exp = self.experiment
        fi = self.file_info
        sol = self.solvent
        mals = self.mals
        ri = self.ri
        uv = self.uv
        visco = self.viscometer
        samp = self.sample
        peaks = self.peaks
        mm = self.get_molar_mass_results()

        return {
            "experiment": {
                "path": exp.path,
                "sample_set_file": exp.sample_set_file,
                "processing_datetime": exp.processing_datetime,
                "astra_version": exp.collection_astra_version,
            },
            "file": {
                "name": fi.file_name,
                "directory": fi.directory,
                "extension": fi.file_extension,
                "created": fi.time_created,
                "modified": fi.time_modified,
                "collected": fi.time_collected,
                "author": fi.author,
                "size_bytes": fi.size,
            },
            "solvent": {
                "name": sol.name,
                "description": sol.description,
                "reference_temperature": sol.reference_temperature,
                "reference_wavelength": sol.reference_wavelength,
                "boiling_point": sol.boiling_point,
            },
            "MALS": {
                "name": mals.name,
                "temperature": mals.temperature,
                "wavelength": mals.wavelength,
                "num_detectors": mals.num_detectors,
                "detector_angles": mals.detector_angles.tolist() if len(mals.detector_angles) > 0 else [],
                "normalization_coefficients": mals.normalization_coefficients.tolist() if len(mals.normalization_coefficients) > 0 else [],
                "calibration_constant": mals.calibration_constant,
                "firmware_version": mals.firmware_version,
            },
            "RI": {
                "name": ri.name,
                "temperature": ri.temperature,
                "wavelength": ri.wavelength,
            },
            "UV": {
                "name": uv.name,
                "cell_length": uv.cell_length,
                "wavelengths": uv.wavelengths,
                "active_channel": uv.active_channel,
            },
            "viscometer": {
                "name": visco.name,
                "temperature": visco.temperature,
                "dilution_factor": visco.dilution_factor,
            },
            "sample": {
                "name": samp.name,
                "dn_dc": samp.dn_dc,
                "concentration": samp.concentration,
                "real_ri": samp.real_ri,
                "primary_uv_wavelength": samp.primary_uv_wavelength,
                "secondary_uv_wavelength": samp.secondary_uv_wavelength,
            },
            "peaks": [
                {
                    "number": p.range_number,
                    "name": p.range_name,
                    "start_min": p.range_start,
                    "end_min": p.range_end,
                    "dn_dc": p.dn_dc,
                    "concentration": p.concentration,
                    "injected_mass": p.injected_mass,
                    "Mn": p.mn,
                    "Mw": p.mw,
                }
                for p in peaks
            ],
            "molar_mass_results": mm,
            "fluid_path": [
                {"from": c.source_instrument, "to": c.destination_instrument, "name": c.name}
                for c in self.fluid_connections
            ],
        }

    # ── Low-level table access ───────────────────────────────────────────

    def list_tables(self) -> list[str]:
        """Return a list of all table names in the database."""
        rows = self._query("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name")
        return [r[0] for r in rows]

    def list_populated_tables(self) -> dict[str, int]:
        """Return a dictionary of {table_name: row_count} for all non-empty tables."""
        result = {}
        for table_name in self.list_tables():
            count = self._query_one(f'SELECT COUNT(*) FROM "{table_name}"')[0]
            if count > 0:
                result[table_name] = count
        return result

    def raw_query(self, sql: str) -> list[tuple]:
        """
        Execute a raw SQL query against the SQLite database.

        Only SELECT statements are permitted; any other statement raises
        ValueError. The connection is also opened read-only and has
        ``PRAGMA query_only=ON`` set, so this guard is defense-in-depth.

        Parameters
        ----------
        sql : str
            SQL query string. Must start with SELECT (case-insensitive).

        Returns
        -------
        list of tuples
            Query results.
        """
        if not sql.lstrip().upper().startswith("SELECT"):
            raise ValueError("raw_query only permits SELECT statements")
        return self._query(sql)

    def get_table_as_dicts(self, table_name: str, limit: Optional[int] = None) -> list[dict]:
        """
        Return all rows from a table as a list of dictionaries.

        Parameters
        ----------
        table_name : str
            Name of the table. Must be present in ``list_tables()``.
        limit : int, optional
            Maximum number of rows to return.

        Returns
        -------
        list of dict
            Each dict maps column name -> value.
        """
        if table_name not in self.list_tables():
            raise ValueError(f"Unknown table: {table_name}")
        sql = f'SELECT * FROM "{table_name}"'
        cur = self._conn.cursor()
        if limit is not None:
            cur.execute(sql + " LIMIT ?", (limit,))
        else:
            cur.execute(sql)
        cols = [d[0] for d in cur.description]
        rows = cur.fetchall()
        cur.close()
        return [dict(zip(cols, row, strict=False)) for row in rows]


# ─────────────────────────────────────────────────────────────────────────────
# CLI / __main__
# ─────────────────────────────────────────────────────────────────────────────

def _main():
    import json
    import sys

    if len(sys.argv) < 2:
        print("Usage: python astra_reader.py <file.afe8> [--summary] [--tables] [--results]")
        sys.exit(1)

    file_path = sys.argv[1]
    reader = AstraReader(file_path)

    if "--tables" in sys.argv:
        print("\n=== Populated Tables ===")
        for name, count in reader.list_populated_tables().items():
            print(f"  {name}: {count} rows")

    if "--summary" in sys.argv or "--tables" not in sys.argv:
        print("\n=== Experiment Summary ===")
        summary = reader.get_summary()
        print(json.dumps(summary, indent=2, default=str))

    if "--results" in sys.argv:
        print("\n=== All Results ===")
        for r in reader.results:
            print(f"  Peak {r.peak} | {r.instrument_name:25s} | {r.data_name:40s} | {r.value:.6g}")

    reader.close()


if __name__ == "__main__":
    _main()
